# To build and run:
# docker build -f Dockerfile.dev -t catalogo_administrativo .
# docker run catalogo_administrativo

# build stage
FROM gradle:9.0.0-jdk21-alpine AS builder

WORKDIR /usr/app/

COPY . .

RUN gradle bootJar

# build runtime
FROM eclipse-temurin:21.0.4_7-jre-alpine

COPY --from=builder /usr/app/build/libs/*.jar /opt/app/application.jar

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

CMD java -jar /opt/app/application.jar